repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: jsonschema2md
        name: Generate JSON Schema Documentation
        entry: bash -c "rm -rf out && jsonschema2md -d . -o docs"
        language: system
        files: '\.json$'
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
